spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
jwt.secret=d28b8afb569de33f132ac8a6a2baea74b1515f0b25dec85ac330df028aa981cc032229995ab64dc464bae8e5686132c3e23e4e6ac248b626887048df371aec93